### ISSUE TITLE
PRs failing to deploy as source branches are not within the branch protection rules for the `Gadi` GitHub Environment

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/access-om2-configs#20]
See annotations of run https://github.com/ACCESS-NRI/access-om2-configs/actions/runs/8059314160

Essentially, the branch protection rules of the `Gadi` GitHub Environment prevent the deployment of PR branches. This is because the branch protection rules that are required to be satisfied (currently `Protected Branches Only`) cannot account for very many PR branch naming schemes. 

**Potential Solutions**
* Allow deployments from any branch (`No Restrictions`) but require a sign off for any deployment. _Simple, but then bottlenecks PRs to the people that can approve deployments._
* Allow deployments from any branch (`No Restrictions`), require a sign off for any deployment, but signing off is done by a bot that checks PR author details. Essentially restricts PR deployment to users that we allow. _More complex, removes potential malicious deployments, restricts PRs._ 
* Allow deployments from `Protected Branches Only`, where we add an all-encompassing branch protection to branches that match `*` (see section on 'multiple branch protected branch rules' in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule), where the only rule is that certain people (ACCESS-NRI staff) can push to these branches. Essentially restricts pushes to all branches to people we allow. Doesn't require code changes, unknown if this affects forks, might be heavy handed. 
* Allow deployments from `Selected Branches and Tags` where we enforce a particular naming convention for PR branches into config branches. For example, `1deg_jra55_iaf-*` for branches that will merge into `1deg_jra55_iaf`. Users don't like being corralled into naming branches certain ways, simpler solution, anyone can PR.
* Imparted divine solution from God Himself that comes to me in a dream 

Tagging @aidanheerdegen, @jo-basevi for input

**Comment by aidanheerdegen** [comment]
We were planning to have `dev-*` branches right? Where the development stuff happens merrily without too much restriction (but maybe helpful CI checks).

So then maybe we can restrict PRs to `release-` to *only* be from the equivalent `dev-` branch. It makes sense to me. Outside PRs to dev, tested away, once happy, or enough useful changes accrue, then a PR from `dev-` to `release-`.

I think the might match one of your possibilities, but not sure which one.
