### ISSUE TITLE
Quantify effects of restart reproducibility on ACCESS-OM2 performance

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-om2-configs#35]
We have a pull request to add restart reproducibility to ACCESS-OM2

https://github.com/ACCESS-NRI/ACCESS-OM2/pull/49

Before we merge this PR, which changes answers so is no longer bitwise reproducible with historical runs, we need to confirm the impacts on performance are modest.

I have done [some testing of the `release-1deg_jra55_ryf` configuration](https://forum.access-hive.org.au/t/testing-spack-model-component-builds-for-access-om2/1567/17).

Representative timings for 5x1 year runs:
```
$ grep PAYU_WALLTIME archive/output*/job.yaml
archive/output000/job.yaml:PAYU_WALLTIME: 827.240124 s
archive/output001/job.yaml:PAYU_WALLTIME: 820.905574 s
archive/output002/job.yaml:PAYU_WALLTIME: 838.12038 s
archive/output003/job.yaml:PAYU_WALLTIME: 819.007872 s
archive/output004/job.yaml:PAYU_WALLTIME: 823.11386 s
```
Average = 826s

After changing to `+restrart_repro`: timings for 5x1 year runs
```
archive/output005/job.yaml:PAYU_WALLTIME: 838.510564 s
archive/output006/job.yaml:PAYU_WALLTIME: 837.38463 s
archive/output007/job.yaml:PAYU_WALLTIME: 833.049087 s
archive/output008/job.yaml:PAYU_WALLTIME: 825.645909 s
archive/output009/job.yaml:PAYU_WALLTIME: 844.943396 s
```
Average = 836s

Performance impact = 1.2% slower.

We need a test for a higher resolution configuration to confirm equivalent performance. I'd suggest we try a 0.1 degree configuration. If it shows comparable performance it probably isn't necessary to run 0.25 degree. 

I would recommend we run `release-01deg_jra55_ryf`.

Experiment design:

1. Clone config: `payu clone -b control -B release-01deg_jra55_ryf https://github.com/ACCESS-NRI/access-om2-configs.git 01deg_jra55_ryf`
2. Change run length to 1 month ([see docs](https://access-hive.org.au/pr-preview/pr-653/models/run-a-model/run-access-om/#change-run-length))
3. Run 5 times: `payu run -n 5`
4. `grep PAYU_WALLTIME archive/output*/job.yaml`
5. [`payu checkout` another experiment](https://payu.readthedocs.io/en/latest/usage.html#switching-between-related-experiments): `payu checkout -b restart-repro` 
6. Change `mom` exe path to `/g/data/vk83/prerelease/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2023.11.09=2023.11.09-qji4nlmr6utrribaiyhewe4je6mifguz/bin/fms_ACCESS-OM.x`
8. Run 5 times: `payu run -n 5`
4. `grep PAYU_WALLTIME archive/output*/job.yaml`

1 month should be sufficient to isolate run time from start-up time, but as an extra check extracting the MOM5 main loop timings might be useful too

```
grep -a 'Main Loop' archive/output00*/access-om2.out
```

As the only change we're making is to MOM5 then it should be a good gauge of the effects of adding restart reproducibility.

**Comment by minghangli-uni** [comment]
### 1. Summary of timings for `release-01deg_jra55_ryf` with 5x1 year runs and a runlength of 1 month:

- `Control experiment` (with runlog on):
Average walltime: 5201s
Individual run times:
```
$ grep PAYU_WALLTIME archive/output*/job.yaml
archive/output000/job.yaml:PAYU_WALLTIME: 5517.617157 s
archive/output001/job.yaml:PAYU_WALLTIME: 5047.3934 s
archive/output002/job.yaml:PAYU_WALLTIME: 5585.16117 s
archive/output003/job.yaml:PAYU_WALLTIME: 4880.420408 s
archive/output004/job.yaml:PAYU_WALLTIME: 4977.883827 s
```
- `Restart-Repro experiment` (with runlog on):
Average walltime: 5254s
Individual run times:
```
grep PAYU_WALLTIME archive/output*/job.yaml
archive/output000/job.yaml:PAYU_WALLTIME: 4986.244727 s
archive/output001/job.yaml:PAYU_WALLTIME: 4522.163586 s
archive/output002/job.yaml:PAYU_WALLTIME: 5010.474077 s
archive/output003/job.yaml:PAYU_WALLTIME: 5096.731212 s
archive/output004/job.yaml:PAYU_WALLTIME: 6657.076611 s
```

**So the performance impact ~ 1% slower, which is consistent with `release-1deg_jra55_ryf`.**

- I did another `restart-repro experiment` but with runlog turning off:
Average walltime: 4884s
```
$ grep PAYU_WALLTIME archive/output*/job.yaml
archive/output000/job.yaml:PAYU_WALLTIME: 4994.581693 s
archive/output001/job.yaml:PAYU_WALLTIME: 4567.629173 s
archive/output002/job.yaml:PAYU_WALLTIME: 4992.140022 s
archive/output003/job.yaml:PAYU_WALLTIME: 4848.478292 s
archive/output004/job.yaml:PAYU_WALLTIME: 5016.793407 s
```

**Performance impact compared to the same restart-repro experiment with runlog on is about 7-8%. Despite this impact, it is still recommended to keep the runlog on for monitoring purposes, with a note on the observed performance reduction.**

### 2. Complete MOM5 main loop timings for reference,
`Control experiment` (with runlog on):
```
$ grep -a 'Main Loop' archive/output00*/access-om2.out
archive/output000/access-om2.out:Main Loop                          5232.323289   5232.423972   5232.325671      0.002035  0.955     0     0  4357
archive/output001/access-om2.out:Main Loop                          4752.816367   4753.134683   4752.875347      0.009411  0.953     0     0  4357
archive/output002/access-om2.out:Main Loop                          5294.320627   5294.366114   5294.357470      0.001536  0.957     0     0  4357
archive/output003/access-om2.out:Main Loop                          4573.308332   4573.320619   4573.313712      0.001183  0.948     0     0  4357
archive/output004/access-om2.out:Main Loop                          4678.141256   4678.156958   4678.147551      0.000819  0.952     0     0  4357
```
`Restart-Repro experiment` (with runlog on):
```
$ grep -a 'Main Loop' archive/output00*/access-om2.out
archive/output000/access-om2.out:Main Loop                          4693.809346   4693.927470   4693.838881      0.005519  0.951     0     0  4357
archive/output001/access-om2.out:Main Loop                          4232.144206   4232.151634   4232.146765      0.000516  0.947     0     0  4357
archive/output002/access-om2.out:Main Loop                          4715.813841   4715.825751   4715.817964      0.000603  0.952     0     0  4357
archive/output003/access-om2.out:Main Loop                          4767.089419   4767.140138   4767.093652      0.001451  0.954     0     0  4357
archive/output004/access-om2.out:Main Loop                          6370.181084   6370.254060   6370.185736      0.001469  0.965     0     0  4357
```
`Restart-Repro experiment` (with runlog off):
```
$ grep -a 'Main Loop' archive/output00*/access-om2.out
archive/output000/access-om2.out:Main Loop                          4690.317663   4690.371832   4690.369220      0.001181  0.952     0     0  4357
archive/output001/access-om2.out:Main Loop                          4259.107689   4259.137033   4259.110759      0.001209  0.948     0     0  4357
archive/output002/access-om2.out:Main Loop                          4702.615846   4702.623691   4702.621459      0.000568  0.953     0     0  4357
archive/output003/access-om2.out:Main Loop                          4541.454916   4541.511143   4541.503021      0.001251  0.949     0     0  4357
archive/output004/access-om2.out:Main Loop                          4722.818765   4722.879631   4722.877333      0.001373  0.952     0     0  4357
```

**Comment by aekiss** [comment]
> ```
> archive/output004/job.yaml:PAYU_WALLTIME: 6657.076611 s
> ```

This runs seems like an outlier and may be skewing the statistics for Restart-Repro (with runlog on).

If we omit this, we get a mean of 4903.9s for Restart-Repro (with runlog on) instead of 5254s, so this is actually faster than the mean for the control (5201s) and essentially the same as restart-repro with runlog off (4884s). This makes more sense to me, as I don't see why runlog would significantly slow things down.

**Comment by aidanheerdegen** [comment]
Very thorough and well documented, thank you @minghangli-uni 

Can I just confirm, when you say runlog off/on, you are referring to the option in `config.yaml`?
```
runlog: True
```
(or `False`)

It's interesting, the runlog on average timings are dominated by one slow run (the 5th). With the outlier removed the `Restart-Repro` with runlog on average Walltime is 4903s.

I think it is clear that it isn't the runlog that is causing the slowness in that aberrant run, as the `Main Loop` timing for MOM is consistent with the slow-down being associated with the model run itself. Probably some transient disk slow-down.

**Comment by aidanheerdegen** [comment]
Heh. Crossed comments @aekiss

**Comment by minghangli-uni** [comment]
> Can I just confirm, when you say runlog off/on, you are referring to the option in `config.yaml`?
> 
> ```
> runlog: True
> ```
> 
> (or `False`)
> 
Yes, it is the option `runlog` in the config.yaml. 
> 
> I think it is clear that it isn't the runlog that is causing the slowness in that aberrant run, as the `Main Loop` timing for MOM is consistent with the slow-down being associated with the model run itself. Probably some transient disk slow-down.

@aekiss @aidanheerdegen I agree. Sorry I didnt check the figures and reached an incorrect conclusion. But anyway, you are cleared to go :)

**Comment by aidanheerdegen** [comment]
No apologies required. Enough information was provided to check this more than adequately. I'll close this now.
