### ISSUE TITLE
Move scripts to sub-directory

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-om2-configs#4]
There are scripts/tools in the top level directory and inside some of the model config directories.

Specifically
```
resub.sh
ocean/make_diag_table.py
```

I propose we create a `scripts` or `tools` directory, put all scripts and their inputs files in that location and keep the model config directories clean of anything but model config information.

This has the added benefit that we can easily exclude a single location from CI reproducibility checks.

**Comment by CodeGat** [comment]
This issue needs to be merged before #1
