### ISSUE TITLE
Additional QA config checks

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/access-om2-configs#45]
This issue is to group together some additional quick QA checks for the model configurations

- [ ] Ensure metadata is enabled, i.e `config.yaml` does not have
```
metadata:
    enable: false
````
- [ ] Ensure `experiment` in `config.yaml` is not set as this over-rides the experiment name used for archival

**Comment by aidanheerdegen** [comment]
Currently we check `license` is set in `metadata.yaml`. 

We've decided the license should be `CC-BY-4.0`

https://github.com/ACCESS-NRI/access-om2-configs/blob/main/CONTRIBUTING.md?plain=1#L126

So we should probably just enforce this in the QA check

**Comment by aidanheerdegen** [comment]
Given that the ice-concatenation works (see https://github.com/ACCESS-NRI/om2-scripts/issues/2) this should be added to the configs and added to the QA checks. 

@jo-basevi I believe it is harmless to have the `sync` userscript defined if `sync` is not enabled, but can you confirm?

**Comment by jo-basevi** [comment]
Yes, the sync user-script will only run if a sync job is enabled or if `payu sync` is run manually.

**Comment by jo-basevi** [comment]
Will also need to add a  pytest for these metadata nominal resolutions check: https://github.com/ACCESS-NRI/access-om2-configs/blob/28719d807e2a2e32abdb377f071ad3c00b87e944/CONTRIBUTING.md?plain=1#L97-L107

**Comment by jo-basevi** [comment]
I'll start a draft PR with these checks so far
