### ISSUE TITLE
Add 0.1 degree BGC configurations

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-om2-configs#48]
Currently only the 0.1 degree RYF and IAF global physics only configurations are available in this repo.

The full ACCESS-OM2 release requires the 0.1 degree configurations, IAF and RYF atmospheric forcing, with bgc.

This corresponds to two configurations:

- [ ] `release-01deg_jra55_ryf_bgc` ([repo](https://github.com/COSIMA/01deg_jra55_ryf/tree/master%2Bbgc))
- [ ] `release-01deg_jra55_iaf_bgc` ([repo](https://github.com/COSIMA/01deg_jra55_iaf/tree/master%2Bbgc))

The [release-01deg_jra55_ryf branch](https://github.com/ACCESS-NRI/access-om2-configs/tree/release-01deg_jra55_ryf) is the template to follow for RYF configurations. Similarly the [release-01deg_jra55_iaf branch](https://github.com/ACCESS-NRI/access-om2-configs/tree/release-01deg_jra55_iaf) is the template to follow for IAF configurations.

The ACCESS-OM2-BGC executables to be used are from this deployment:

https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/releases/tag/2024.03.0

The [spack.location file ](https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/releases/download/2024.03.0/spack.location)gives the paths to the installed components:

```
=> In environment access-om2-bgc-2024_03_0
==> Root specs
access-om2-bgc@git.2024.03.0=2024.03.0

==> Installed packages
-- linux-rocky8-x86_64 / intel@19.0.5.281 -----------------------
access-om2-bgc@git.2024.03.0=2024.03.0  /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/access-om2-bgc-git.2024.03.0=2024.03.0-kvkkuxlofjkqxat5nx6gu5d2lerjizk4
cice5@git.2023.10.19=2023.10.19         /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/cice5-git.2023.10.19=2023.10.19-v3zncpqjj2gyseudbwiudolcjq3k3leo
cmake@3.24.2                            /apps/cmake/3.24.2
datetime-fortran@1.7.0                  /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/datetime-fortran-1.7.0-aretozixwsdz42owabgzeiuxooyxrspg
gmake@4.4.1                             /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/gmake-4.4.1-ugorlm6e6s5hkwsandqvyrdtwwq3mckf
hdf5@1.14.1-2                           /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/hdf5-1.14.1-2-a6mpuk7tw5e4pyukxwalooc7jfldalcf
json-fortran@8.3.0                      /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/json-fortran-8.3.0-nyxvikkez6fu64xtbeqqz2a4wngikfgi
libaccessom2@git.2023.10.26=2023.10.26  /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/libaccessom2-git.2023.10.26=2023.10.26-ltfg7jcn6t4cefotvj3kjnyu5nru26xo
mom5@git.2023.11.09=2023.11.09          /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-git.2023.11.09=2023.11.09-64l5azdtcoxhrgb5ynn2vued5lmjvn33
netcdf-c@4.7.4                          /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/netcdf-c-4.7.4-i3inxzaihefr3rqljoovhyevwai6bsff
netcdf-fortran@4.5.2                    /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/netcdf-fortran-4.5.2-mnx4gghyb5gngsl3fgosud6k72yu2u6a
oasis3-mct@git.2023.11.09=2023.11.09    /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/oasis3-mct-git.2023.11.09=2023.11.09-sh2anmtjrygzixya2fjc3p7cg4o5wc5h
openmpi@4.0.2                           /apps/openmpi/4.0.2
parallelio@2.5.2                        /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/parallelio-2.5.2-nwolfzy2xxb4wub65gmvlm3edhuolmlh
pkgconf@1.9.5                           /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/pkgconf-1.9.5-uyq7tvpnuuo3gosnplkvuxktaeeipuqk
zlib@1.2.13                             /g/data/vk83/apps/spack/0.20/release/linux-rocky8-x86_64/intel-19.0.5.281/zlib-1.2.13-arj4bfz33zf63gvfionhorrrveci6kb4
```

### Steps to follow to add a COSIMA configuration to this repo:

1. Clone this repo, e.g. `gh repo clone ACCESS-NRI/access-om2-configs`
2. Clone configuration repo, e.g. `gh repo clone COSIMA/01deg_jra55_ryf`
3. `cd access-om2-configs`
5. Add the COSIMA repo as a remote, e.g. `remote add 01deg_jra55_ryf ../01deg_jra55_ryf`
6. Create branch from config repo, e.g. `git checkout  -b dev-01deg_jra55_ryf_bgc 01deg_jra55_ryf/master+bgc`
7. Modify configuration to only use paths from `vk83` and `qv56`
8. Add configuration to GitHub repository, e.g. `git push -f dev-1deg_jra55_ryf_bgc`

### Steps to modify a configuration:

1. Change the run length to something short for testing purposes (maybe a few time steps for 0.1 degree configurations)
1. Create a ground-truth from the COSIMA configuration to compare against. Make sure you have diagnostic output at a high enough frequency that fields are output for the shortened run length. Good fields to choose are prognostic variables like salt, temp and velocities u, v.
1. Create a tools subdirectory and git mv scripts to this location. Update config.yaml as required
1. Modify input paths to point to the new structure in `vk83` (see 1 degree physics only configuration which is identical apart from BGC only inputs)
1. Turn off runlog to prevent unnecessary git commits during testing
1. Run short test run and check reproducibility (this should be reproducible as only input locations have changed)
1. Modify the configuration by changing paths to executables to those in `vk83` (see paths above and 1 degree physics only config which is identical except for MOM5 path, and note there are different CICE executables for the different resolutions)
1. Run short test run and check differences are minimal (see "Reproducibility Testing" below)
1. Update README
1. Change run length back, and turn runlog back on
1. `git checkout` new branch and add and commit changes made above
1. `git push` new branch to repository and create a pull request to the `dev-*` branch created and pushed in first section
1. Fix all QA tests which fail in the CI testing. See [Contributing Guide](https://github.com/ACCESS-NRI/access-om2-configs/blob/main/CONTRIBUTING.md) for an explanation of some the tests and what is typically required for a conforming configuration.
1. Once all QA tests are passing and PR is merged [create a release branch and add reproducibility checksums following the instructions](https://github.com/ACCESS-NRI/access-om2-configs/blob/main/CONTRIBUTING.md#create-a-new-release-branch). In this case specify the initial version to be `2.0` to indicate that this is no longer bit reproducible with the COSIMA (1.0) versions.
1. Add summary of testing done to this issue, and include `access-om2.out` log files to be a ground truth if required in the future

This GitHub comparison shows the changes required for the 0.1 degree RYF physics only configuration:

https://github.com/ACCESS-NRI/access-om2-configs/compare/aea51fa...3d02f7e

### Reproducibility Testing

We no longer have bit reproducibility with historical (COSIMA) versions of ACCESS-OM2 because we have opted to turn on compile options to ensure we have reproducibility across restarts.

However the outputs should remain bit reproducible until the point where executables are modified.

Regardless, even when the executables are modified it is a good idea to run the model to check the differences after a short time are what we'd expect: just some noise in the fields.

For comparing model outputs  I recommend a few different tools:

- `nccmp` (`/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.07/bin/nccmp`)

`nccmp` is silent when files are equivalent, otherwise it will echo to STDERR whether metadata or a specific variable differs.  By default, comparing stops after the first difference.                   

- `ncdiff` (`/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.07/bin/ncdiff`)

`ncdiff` subtracts one netcdf file from another

- `ncview` (`/apps/ncview/2.1.7/bin/ncview`)

Simple Xwindows based netCDF file viewer. When subtracting one file from another it is a good idea to make sure the files contain actual data. If they're empty you may get a false negative for bit reproducibility as they will be identical.

Edit: this has been edited on 3/4 to better reflect the process for creating `dev-` and `release-` branches from scratch.

**Comment by aidanheerdegen** [comment]
I am trying to determine what should be in the `notes` field of the `metadata.yaml`. There is a late [issue with licensing](https://github.com/COSIMA/access-om2/issues/264#issuecomment-2036090733) I need to clear up.

**Comment by aidanheerdegen** [comment]
I have updated the 1 degree BGC instructions, hopefully made it a little clearer and also added an option to not require running the model

https://github.com/ACCESS-NRI/access-om2-configs/issues/19#issue-2158145130

I haven't updated the instructions above as I know you're in the middle of this process @minghangli-uni, but I can if you think it's useful I can do so, it would take very little time (cut n' paste and search and replace 1deg for 01deg).

**Comment by minghangli-uni** [comment]
Thank you @aidanheerdegen. I'll review the comments on https://github.com/ACCESS-NRI/access-om2-configs/issues/19#issue-2158145130. That should provide the necessary information for me.

**Comment by minghangli-uni** [comment]
# Testing of `01deg_jra55_ryf_bgc` configuration:
Followed [Option 2 in issue #19](https://github.com/ACCESS-NRI/access-om2-configs/issues/19#issue-2158145130):

- [ ] successfully ran configuration for 2 days.

- [ ] For the purpose of ensuring checksum reproducibility, the output file from a Known Good Output (KGO) generated by the COSIMA configuration and the output file from the current configuration are provided below:

```
/g/data/tm70/ml0072/access-om2-configs/BIT-REPRO/om2-config-01deg_jra55_ryf+bgc/access-om2.out
/g/data/tm70/ml0072/access-om2-configs/BIT-REPRO/om2-cosima-01deg_jra55_ryf+bgc/access-om2.out
```

- [ ] The outputs generated from both models are compared using tools,

- `nccmp (/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.07/bin/nccmp)`
- `ncdiff (/g/data/hh5/public/apps/miniconda3/envs/analysis3-23.07/bin/ncdiff)`
-  `ncview (/apps/ncview/2.1.7/bin/ncview)`

- [ ] The comparison ensures that the files contain actual data and confirms that the outputs are identical.

**Comment by minghangli-uni** [comment]
# Testing of `1deg_jra55_iaf_bgc` configuration:
Followed [Option 1 in issue #19](https://github.com/ACCESS-NRI/access-om2-configs/issues/19#issue-2158145130):
- [x] inputs: no `md5` hash changed, a few `binhash` hashes changed
- [x] exes: all `md5` and `binhash` hashes changed
- [x] successfully ran configuration for 2 days.

**Comment by aidanheerdegen** [comment]
Nice work, this is done.
