### ISSUE TITLE
Add keyword to flag BGC runs

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-om2-configs#62]
Can we add a keyword to flag BGC runs to [the list of allowable keywords in the QA tests](https://github.com/ACCESS-NRI/access-om2-configs/blob/b845231565c557dcee7989a16f5f4c258282ddf5/test/test_access_om2_config.py#L10-L16)? E.g. `"bgc"`? 

Some relevant discussion in https://github.com/ACCESS-NRI/access-om2-configs/issues/25

**Comment by aidanheerdegen** [comment]
It's a good point. 

Can you suggest a new "topic" for that keyword? For good or ill we've made all keywords in a topic mutually exclusive. A decision I'm not entirely sure about now.

**Comment by dougiesquire** [comment]
Um `'model variant'`? It's not great...
