### ISSUE TITLE
New workflow for creating initial checksum truth

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-om2-configs#9]
The first time a new release configuration is added to the repo it will need a checksum file for the CI checks in a PR can compare against it.

This means the person adding the configuration would need to clone this repo and manually run the `pytest` check on `gadi`, generate the checksum file and add it to the new configuration.

This is undesirable for a number of reasons:
1. Places a burden on the person creating the configuration
2. Error prone: requires running the correct tests in the appropriate way with correct configured tools (such as `payu`)
3. Does not faithfully reproduce the same environment as that used in the CI, meaning answers might not be exactly the same
4. There is no way to check "the truth" is true. There is no independent CI check that confirms the CI process reproduces this truth

If there was a dispatchable workflow that could be run to generate a checksum truth for a branch this would alleviate 1-3.

If there was another workflow to confirm the checksum file is correct that would be cool. Usually the CI would check against the target branch. Is there a way to get it to compare against the PR branch? Then updating a checksum could be done in a PR and checked for correctness. Hrm.

**Comment by CodeGat** [comment]
Currently I'm considering a reusable `workflow_dispatch` workflow that would generate the checksum at a particular config branch that would optionally commit it directly to a given branch. If we choose not to commit it directly, we would still be given the location on Gadi that the checksums were generated on.
