### ISSUE TITLE
New CICE grids

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/access-om2-configs#92]
Per https://github.com/COSIMA/om3-utils/pull/5, there are updated cice grids at all resolutions, this requires updating all 0.1 and 1 degree config.yaml files. (0.25 is implemented in #17)

**Comment by aidanheerdegen** [comment]
Hey @bschroeter any opinions about what metadata should be included?

We should probably start using something like axiom to validate against a schema

https://axiom.readthedocs.io/en/latest/schemas/schemas.html

Though that is a much wider problem, so have created an issue

https://github.com/ACCESS-NRI/access-om2-configs/issues/101

**Comment by anton-seaice** [comment]
> It can't determine axes. If that was desirable there would need to be variables added for `nx` and `ny` with an appropriate non-tripolar cartesian grid (similar to what MOM does).
> 
> http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#_two_dimensional_latitude_longitude_coordinate_variables

Yes. That is correct. There are a few things to note:

- The axis in our case do not have a physical meaning. All analysis needs to use the 2D geolon and geolate fields.
- From your link, X and Y axis are defined in metres in a Cartesian system. Our grid does contain this information.
- CICE doesn't use these fields, so to reduce confusion we wouldn't add them to this file.

>     1. Ice output grids contained NAs which required to read in the `grid.nc` file to get unmasked lat/lon grids

I obviously can't solve that here.

>     2. The `grid.nc` file has different dimensions names to the output data (`ni`, `nj` in data vs `nx`, `ny` in the grid file)

We might be able to change this. Ill catch this in https://github.com/COSIMA/esmgrids/issues/16

>     3. The grid uses units of radians (which seems incredibly unusual, but would be difficult to modify if the model is expecting radians)

I obviously can't solve that here either.


> I ran the file through the [CF compliance checker](http://climate-cms.wikis.unsw.edu.au/CF_checker)
> Details

We will look at this in more detail for OM3 in conjunction with looking at the output files. 

For OM2, we are releasing the current configuration and don't need to do anything further.

**Comment by aidanheerdegen** [comment]
All related PRs are merged so will close.
